
def cover(ali_log):

	ali_log.write(f"..................................................................................................\n")
	ali_log.write(f"  ..........................................................................................\n")
	#ali_log.write(f"    ......................................................................................\n")
	#ali_log.write(f"      .................................................................................\n")
	ali_log.write(f"                                      														    \n")                  
	#ali_log.write(f"                                        .  .                        \n")
	#ali_log.write(f"                                                                    \n")
	#ali_log.write(f"                               ...    ..  ....                      \n")
	#ali_log.write(f"                           .........        ....                    \n")
	#ali_log.write(f"                          ............        ....                  \n")
	#ali_log.write(f"                          .............      ......   .             \n")
	#ali_log.write(f"                          .............       .....       .         \n")
	#ali_log.write(f"                          ..............                ....        \n")
	#ali_log.write(f"                            ...................         ......      \n")
	#ali_log.write(f"                              ....................          ....    \n")
	#ali_log.write(f"                                  ...............           ....    \n") 
	#ali_log.write(f"                                    ................      ......... \n")
	#ali_log.write(f"                   .  .             .................   ........... \n")
	#ali_log.write(f"                   .   ..       ..   ................. ............ \n")
	#ali_log.write(f"                    .  .....  ...... ................  ...........  \n")
	#ali_log.write(f"                          ..........   .............    .........   \n")
	#ali_log.write(f"                              .....      ...........      ......    \n")
	#ali_log.write(f"                                            .  .                    \n")
	#ali_log.write(f"                                           ........                 \n")
	#ali_log.write(f"                                        ...........                 \n")
	#ali_log.write(f"                           .  .   .      ............               \n")
	#ali_log.write(f"                               ....      ............               \n")
	#ali_log.write(f"                              . .....     ...........               \n")
	#ali_log.write(f"                                   ................                 \n")
	#ali_log.write(f"                                      ..........                    \n")
	#ali_log.write(f"                                      														    \n")           
	#ali_log.write(f"           ......  .........  .........  .........  .........  ...   ...  .........        	\n")
	#ali_log.write(f"         ........  .........  .........  .........  .........  ...   ...  .........        	\n")   
	#ali_log.write(f"        ...        ...   ...  ...   ...     ...     ...        .... ....  ...   ...        	\n")
	#ali_log.write(f"        ...        ...   ...  ...   ...     ...     ...        .... ....  ...   ...        	\n")
	#ali_log.write(f"        ...        .........  .........     ...     .........  ... . ...  .........        	\n")
	#ali_log.write(f"        ...        .........  .........     ...     .........  ...   ...  .........        	\n")
	#ali_log.write(f"        ...        ...        ... ...       ...           ...  ...   ...  ...   ...        	\n")
	#ali_log.write(f"         ........  ...        ...  ...   .........  .........  ...   ...  ...   ...        	\n")
	#ali_log.write(f"           ......  ...        ...   ...  .........  .........  ...   ...  ...   ...        	\n\n\n")
	ali_log.write(f"                                        CPRISMA - 2021 \n\n          ")
	ali_log.write(f"                           CPRISMA is written by:          \n\n")
	ali_log.write(f"                                 Sergio Alejandro Poveda Cuevas \n")
	ali_log.write(f"                                      seapovedac@gmail.com\n\n")
	ali_log.write(f"    CPRISMA is a bioinformatics program that gives color to multiple sequence alignment based on an input of numerical data.\n\n")
	#ali_log.write(f"      .................................................................................\n")
	#ali_log.write(f"    ......................................................................................\n")
	ali_log.write(f"  ..........................................................................................\n")
	ali_log.write(f"..................................................................................................\n\n")

	print(f"                                  CPRISMA - 2021           ")
	print(f"                              CPRISMA is written by:          ")
	print(f"                          Sergio Alejandro Poveda Cuevas ")
	print(f"                               seapovedac@gmail.com\n")
	print(f"  CPRISMA is a bioinformatics program that gives color to multiple sequence alignment based on an input of numerical data.\n")

